M48
; DRILL file {KiCad 9.0.1} date 2025-10-12T18:30:31-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-12T18:30:31-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.550
%
G90
G05
T1
X122.61Y-59.72
X128.39Y-59.72
T2
X109.975Y-41.1
X109.975Y-61.93
M30
