------------------------------------------------------------------------------------
-- The big idea behind this schema is that the database is stored in a single file.
-- Every time the "new session" command is send from the pit, a new .db file is
-- created. Associated with this file is a timestamp in the form YYYY-MM-DDTHH:SSZ
-- (conforming to the ISO 8601 standard)
-- The z means "Zulu time", otherwise known as an offset of 0 from UTC. (The name of 
-- the file is really only used as a unique identifier, so it's not actually that
-- important)
--
-- [The paragraph below is still theoretical and a WIP]
-- All of these sessions are stored locally on a flash drive on the car. Once 
-- somebody with the flash drive has access to the Postgres server, they can sync
-- up all of the locally stored data with the rest of the data. The syncing process
-- will also clear the data on the flash drive, eliminating the need to manually 
-- clean it. Each .db file will be treated as its own unique session in the Postgres
-- database
--
-- [Fever dream goal below]
-- Eventually, it would be really cool to set up a web service that uses the postgres
-- database in combination with a data visualizer (Grafana?). It would also be really
-- cool to have this as a service that other teams could set up with their own 
-- telemetry systems.
--
-- Originally written by Matthew Larson
-- Started August 27, 2025
------------------------------------------------------------------------------------



-- Why aren't foreign keys enabled by default? No clue.
PRAGMA foreign_keys = ON;

-- Performance optimization (add more information here)
PRAGMA journal_mode = WAL;
-- Another performance optimization. Should probably give some more information
PRAGMA synchronous = NORMAL;


CREATE TABLE IF NOT EXISTS vehicle(
	name VARCHAR(128) PRIMARY KEY,
	competition_year DATETIME NOT NULL
	-- Should probably add more fields later?
);

CREATE TABLE IF NOT EXISTS log(
	id INTEGER PRIMARY KEY,
	epoch INTEGER,
	vehicle VARCHAR(128), -- make foreign key constraint
	type VARCHAR(16) NOT NULL, -- ie. Log, Warning, Error, Panic, etc.
	message TEXT,
	FOREIGN KEY(vehicle) REFERENCES vehicle(name)
);


CREATE TABLE IF NOT EXISTS sensor(
	name VARCHAR(128) PRIMARY KEY,
	manufacturer TEXT NOT NULL,
	model TEXT NOT NULL,
	sensor_type TEXT NOT NULL,
	description TEXT
);


CREATE TABLE IF NOT EXISTS imu(
	epoch INTEGER,
	vehicle VARCHAR(128), -- make foreign key constraint
	sensor VARCHAR(128), -- make foreign key constraint
	ax REAL,
	ay REAL,
	az REAL,
	-- other stuff, idk what we want yet
	ax_unit VARCHAR(32) GENERATED ALWAYS AS ('m/s^2') VIRTUAL,
	FOREIGN KEY(vehicle) REFERENCES vehicle(name),
	FOREIGN KEY(sensor) REFERENCES sensor(name)
);


CREATE TABLE IF NOT EXISTS temperature(
	epoch INTEGER,
	vehicle VARCHAR(128), -- make foreign key constraint
	sensor VARCHAR(128), -- make foreign key constraint
	temp REAL,
	temp_unit VARCHAR(32) GENERATED ALWAYS AS ('°C') VIRTUAL,
	FOREIGN KEY(vehicle) REFERENCES vehicle(name),
	FOREIGN KEY(sensor) REFERENCES sensor(name)
);


CREATE TABLE IF NOT EXISTS tachometer(
	epoch INTEGER,
	vehicle VARCHAR(128), -- make foreign key constraint
	sensor VARCHAR(128), -- make foreign key constraint
	rpm REAL, 	-- No need for a unit. It's literally in the name
	FOREIGN KEY(vehicle) REFERENCES vehicle(name),
	FOREIGN KEY(sensor) REFERENCES sensor(name)
);


-- This table is for data that is not generated by a particular sensor, but rather
-- a collection of sensors or some other value.
CREATE TABLE IF NOT EXISTS vehicle_state(
	epoch INTEGER,
	vehicle VARCHAR(128), -- make foreign key constraint
	speed REAL,
	dist REAL,
	
	speed_unit VARCHAR(32) GENERATED ALWAYS AS ('m/s'),
	dist_unit VARCHAR(32) GENERATED ALWAYS AS ('m'),
	
	FOREIGN KEY(vehicle) REFERENCES vehicle(name)
);
