-----------------------------------------------------------------------------
--
--
--
--
--
-----------------------------------------------------------------------------



-- Why aren't foreign keys enabled by default? No clue.
PRAGMA foreign_keys = ON;

-- Performance optimization (add more information here)
PRAGMA journal_mode = WAL;
-- Another performance optimization. Should probably give some more information
PRAGMA synchronous = NORMAL;

-- As opposed to the 2024-2025 database, this database does not have a "session" table.
-- This is because this year, each session will be represented as a separate .db file with an associated date.
-- Occasionally, we will take the local files and upload them to a separate postgres database that holds session information
-- Postgres is much better for managing large amounts of data

CREATE TABLE IF NOT EXISTS log(
	id INTEGER PRIMARY KEY,
	vehicle VARCHAR(128), -- make foreign key constraint
	type VARCHAR(16) NOT NULL, -- ie. Log, Warning, Error, Panic, etc.
	message TEXT
);

CREATE TABLE IF NOT EXISTS vehicle(
	name VARCHAR(128) PRIMARY KEY,
	competition_year DATETIME NOT NULL,
	
);

CREATE TABLE IF NOT EXISTS sensors(
	name VARCHAR(128) PRIMARY KEY,
	manufacturer TEXT NOT NULL,
	model TEXT NOT NULL,
	sensor_type TEXT NOT NULL,
	description TEXT
);


CREATE TABLE IF NOT EXISTS imu(
	epoch INTEGER,
	vehicle VARCHAR(128), -- make foreign key constraint
	sensor VARCHAR(128), -- make foreign key constraint
	ax REAL,
	ay REAL,
	az REAL,
	-- other stuff, idk what we want yet
	ax_unit VARCHAR(32) GENERATED ALWAYS AS ('m/s^2') VIRTUAL,
);


CREATE TABLE IF NOT EXISTS temperature(
	epoch INTEGER,
	vehicle VARCHAR(128), -- make foreign key constraint
	sensor VARCHAR(128), -- make foreign key constraint
	temp REAL,
	temp_unit VARCHAR(32) GENERATED ALWAYS AS ('°C') VIRTUAL,
);


CREATE TABLE IF NOT EXISTS tachometer(
	epoch INTEGER,
	vehicle VARCHAR(128), -- make foreign key constraint
	sensor VARCHAR(128), -- make foreign key constraint
	value REAL,
	value VARCHAR(32) GENERATED ALWAYS AS ('rad/s') VIRTUAL
);


-- This table is for data that is not generated by a particular sensor, but rather
-- a collection of sensors or some other value.
CREATE TABLE IF NOT EXISTS vehicle_state(
	epoch INTEGER,
	vehicle VARCHAR(128), -- make foreign key constraint
	speed REAL,
	dist REAL,
	
	speed_unit VARCHAR(32) GENERATED ALWAYS AS ('m/s'),
	dist_unit VARCHAR(32) GENERATED ALWAYS AS ('m')
);
